services:
  db:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - ./db:/docker-entrypoint-initdb.d  # Mount seed folder
      - ./volumes/db_data:/data/db  
    networks:
      p4-net:
        ipv4_address: 172.20.0.10

  main:
    build:
      context: .
      dockerfile: main.Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://172.20.0.10:27017/flowerbudsboutique
      - SESSION_SECRET=secretkey
      - LOGIN_API_URL=http://172.20.0.12:5001    # main -> login backend
      - LOGIN_PUBLIC_URL=http://localhost:5001   # main -> tells browser to go here
    networks:
      p4-net:
        ipv4_address: 172.20.0.11
    develop:
      watch:
        - action: sync
          path: ./controllers/
          target: /app/controllers/
          #ignore: [ "node_modules/" ]
        - action: sync
          path: ./public/
          target: /app/public/
        - action: sync
          path: ./schemas/
          target: /app/schemas/
        - action: sync
          path: ./server/
          target: /app/server/
        - action: sync
          path: ./views/
          target: /app/views/
        - action: sync
          path: ./index.js
          target: /app/index.js
        - action: rebuild
          path: ./package.json
          target: /app/package.json
        - action: rebuild
          path: ./main.Dockerfile
          target: /app/main.Dockerfile
      
  login:
    build:
      context: .
      dockerfile: login.Dockerfile
    depends_on:
      - db
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb://172.20.0.10:27017/flowerbudsboutique
      - SESSION_SECRET=secretkey
      - MAIN_API_URL=http://172.20.0.11:5000     # login -> main backend
      - MAIN_PUBLIC_URL=http://localhost:5000    # login -> tells browser
    networks:
      p4-net:
        ipv4_address: 172.20.0.12
    develop:
      watch:
        - action: sync
          path: ./controllers/
          target: /app/controllers/
        - action: sync
          path: ./public/
          target: /app/public/
        - action: sync
          path: ./schemas/
          target: /app/schemas/
        - action: sync
          path: ./server/
          target: /app/server/
        - action: sync
          path: ./views/
          target: /app/views/
        - action: sync
          path: ./login.js
          target: /app/login.js
        - action: rebuild
          path: ./package.json
          target: /app/package.json
        - action: rebuild
          path: ./login.Dockerfile
          target: /app/login.Dockerfile

networks:
  p4-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16  # this range must contain the 2 IPs above